#!/usr/bin/env bash

start=$(pwd)

# https://caml.inria.fr/pub/docs/manual-ocaml/lexyacc.html
cd $WD/src/
ocamllex lexer.mll      # generates lexer.ml
ocamlyacc parser.mly    # generates parser.ml and parser.mli
ocamlc -c parser.mli
ocamlc -c lexer.ml
ocamlc -c parser.ml
ocamlc -c calc.ml
ocamlc -o $WD/bin/calc lexer.cmo parser.cmo calc.cmo

cd $start

rlwrap $WD/bin/calc
