#!/usr/bin/env bash

set -eu

build () {
    home=$(pwd)
    cd $WD/build
    for x in prelude.ml lexer.mll parser.mly main.ml; do
        cp $WD/src/$x ./$x
    done
    ocamllex lexer.mll
    menhir parser.mly
    ocamlc prelude.ml -c parser.mli
    ocamlc lexer.ml parser.ml main.ml -o $WD/bin/main
    cd $home
}

build
rlwrap $WD/bin/main
