#!/usr/bin/env bash

set -eu

build () {
    home=$(pwd)
    if [ ! -d $WD/build ]; then
        mkdir $WD/build
    fi
    cd $WD/build
    for x in lexer.mll parser.mly main.ml; do
        cp $WD/src/$x ./$x
    done
    ocamllex lexer.mll
    menhir parser.mly
    ocamlc -c parser.mli
    ocamlc lexer.ml parser.ml main.ml -o $WD/bin/main
    cd $home
}

build
rlwrap $WD/bin/main
