#!/usr/bin/env bash

set -eu

build () {
    cd "$WD/pprint/build"
    cp "$WD/pprint/src/main.ml" ./
    ocamlc main.ml \
        -w +1..66-4-48 \
        -o "$WD/pprint/bin/main"
}

build
rlwrap "$WD/pprint/bin/main"
